name: Ruff

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

env:
    RUFF_OUTPUT_FORMAT: github
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --exit-non-zero-on-fix --verbose
      - run: ruff format --check --verbose